# Railway Configuration
# This tells Railway to build from the frontend folder

[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

